version: "3"
 
services:
  mongo1:
    image: mongo
    command: --replSet my-mongo-set
    ports:
      - 27017:27017
 
  mongo2:
    image: mongo
    command: --replSet my-mongo-set
 
  mongo3:
    image: mongo
    command: --replSet my-mongo-set
     
networks:
  default:
    external:
      name: my-network
